version: '3'
services:
  db:
    image: postgres
    env_file: ./db.env
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./db.env
    ports:
      - "8080:8080"
    depends_on:
      - db