version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    depends_on:
      - redis
    env_file:
      - go.env
  redis:
    image: redis:6
    env_file:
      - go.env
