version: '3.9'
services:
    secrets.service:
        container_name: secrets.service
        build:
            context: .
            dockerfile: docker/secretsd/Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - secrets.mongodb
    secrets.gc:
        container_name: secrets.gc
        build:
            context: ./
            dockerfile: docker/secretsgcd/Dockerfile
        depends_on:
            - secrets.mongodb
    secrets.mongodb:
        container_name: secrets.mongodb
        image: mongo
        hostname: secrets.mongodb
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
