// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Secret Server
//
//  This is an API of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certen number of views or after a certen period of time.
//  Schemes:
//    http
//  Host: api.your-secret-server.com
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - application/json
//    - application/xml
//
// swagger:meta
package restapi
