// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wp-atrd-task/models"
)

// AddSecretOKCode is the HTTP code returned for type AddSecretOK
const AddSecretOKCode int = 200

/*AddSecretOK successful operation

swagger:response addSecretOK
*/
type AddSecretOK struct {

	/*
	  In: Body
	*/
	Payload *models.Secret `json:"body,omitempty"`
}

// NewAddSecretOK creates AddSecretOK with default headers values
func NewAddSecretOK() *AddSecretOK {

	return &AddSecretOK{}
}

// WithPayload adds the payload to the add secret o k response
func (o *AddSecretOK) WithPayload(payload *models.Secret) *AddSecretOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add secret o k response
func (o *AddSecretOK) SetPayload(payload *models.Secret) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddSecretOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddSecretMethodNotAllowedCode is the HTTP code returned for type AddSecretMethodNotAllowed
const AddSecretMethodNotAllowedCode int = 405

/*AddSecretMethodNotAllowed Invalid input

swagger:response addSecretMethodNotAllowed
*/
type AddSecretMethodNotAllowed struct {
}

// NewAddSecretMethodNotAllowed creates AddSecretMethodNotAllowed with default headers values
func NewAddSecretMethodNotAllowed() *AddSecretMethodNotAllowed {

	return &AddSecretMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddSecretMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
