// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSecretByHashHandlerFunc turns a function with the right signature into a get secret by hash handler
type GetSecretByHashHandlerFunc func(GetSecretByHashParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSecretByHashHandlerFunc) Handle(params GetSecretByHashParams) middleware.Responder {
	return fn(params)
}

// GetSecretByHashHandler interface for that can handle valid get secret by hash params
type GetSecretByHashHandler interface {
	Handle(GetSecretByHashParams) middleware.Responder
}

// NewGetSecretByHash creates a new http.Handler for the get secret by hash operation
func NewGetSecretByHash(ctx *middleware.Context, handler GetSecretByHashHandler) *GetSecretByHash {
	return &GetSecretByHash{Context: ctx, Handler: handler}
}

/*GetSecretByHash swagger:route GET /secret/{hash} secret getSecretByHash

Find a secret by hash

Returns a single secret

*/
type GetSecretByHash struct {
	Context *middleware.Context
	Handler GetSecretByHashHandler
}

func (o *GetSecretByHash) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSecretByHashParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
